// examples/starknet-react-next/src/components/TransferEth.tsx
"use client";

import { Button } from "@cartridge/ui-next";
import { useAccount, useExplorer } from "@starknet-react/core";
import { useCallback, useState } from "react";

const ETH_CONTRACT =
  "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7";

export const TransferEth = () => {
  const [submitted, setSubmitted] = useState<boolean>(false);
  const { account } = useAccount();
  const explorer = useExplorer();
  const [txnHash, setTxnHash] = useState<string>();

  const execute = useCallback(
    async (amount: string) => {
      if (!account) {
        return;
      }
      //setSubmitted(true);
      setTxnHash(undefined);

//       await account.estimateInvokeFee(
// [
//           {
//             contractAddress: ETH_CONTRACT,
//             entrypoint: "approve",
//             calldata: [account?.address, amount, "0x0"],
//           },
//           {
//             contractAddress: ETH_CONTRACT,
//             entrypoint: "transfer",
//             calldata: [account?.address, amount, "0x0"],
//           },
//         ]);

      account
        .execute([
          {
            contractAddress: ETH_CONTRACT,
            entrypoint: "approve",
            calldata: [account?.address, amount, "0x0"],
          },
          {
            contractAddress: ETH_CONTRACT,
            entrypoint: "transfer",
            calldata: [account?.address, amount, "0x0"],
          },
        ]);
        // .then(({ transaction_hash }) => setTxnHash(transaction_hash))
        // .catch((e) => console.error(e))
        // .finally(() => setSubmitted(false));
    },
    [account],
  );

  if (!account) {
    return null;
  }

  return (
    <div>
      <h2>Session Transfer Eth</h2>
      <p>Address: {ETH_CONTRACT}</p>
      <Button onClick={() => execute("0x0")} disabled={submitted}>
        Transfer 0 ETH to self
      </Button>
      <Button onClick={() => execute("0x1C6BF52634000")} disabled={submitted}>
        Transfer 0.005 ETH to self
      </Button>
      <Button
        onClick={() => execute("1B1AE4D6E2EF500000")}
        disabled={submitted}
      >
        Transfer 500 ETH to self
      </Button>
      {txnHash && (
        <p>
          Transaction hash:{" "}
          <a
            href={explorer.transaction(txnHash)}
            target="_blank"
            rel="noreferrer"
          >
            {txnHash}
          </a>
        </p>
      )}
    </div>
  );
};

// examples/svelte/src/components/TransferEth.svelte
<script lang="ts">
	import { AccountInterface } from 'starknet';
	import { ETH_CONTRACT } from '../constants';
	export let account: AccountInterface | undefined;

	let txnHash: string | undefined;
	let isSubmitted: boolean = false;

	async function execute(amount: string, manual: boolean) {
		if (!account) {
			return;
		}

		txnHash = undefined;
		isSubmitted = true;

		account
			.execute([
				{
					contractAddress: ETH_CONTRACT,
					entrypoint: manual ? 'increaseAllowance' : 'approve', // increaseAllowance is not part of policies so controller will prompt confirmation
					calldata: [account.address, amount, '0x0']
				},
				{
					contractAddress: ETH_CONTRACT,
					entrypoint: 'transfer',
					calldata: [account.address, amount, '0x0']
				}
			])
			.then(({ transaction_hash }) => {
				txnHash = transaction_hash;
			})
			.catch((e) => console.error(e))
			.finally(() => {
				isSubmitted = false;
			});
	}
</script>

<h2>Transfer Eth</h2>
<p>Address: {ETH_CONTRACT}</p>
<div>
	<h4>Session</h4>
	<button on:click={() => execute('0x0', false)} disabled={isSubmitted}>
		Transfer 0 ETH to self</button
	>
	<button on:click={() => execute('0x1C6BF52634000', false)} disabled={isSubmitted}>
		Transfer 0.005 ETH to self</button
	>
	<button on:click={() => execute('1B1AE4D6E2EF500000', false)} disabled={isSubmitted}>
		Transfer 500 ETH to self</button
	>

	<h4>Manual</h4>
	<button on:click={() => execute('0x0', true)} disabled={isSubmitted}>
		Transfer 0 ETH to self</button
	>
	<button on:click={() => execute('0x1C6BF52634000', true)} disabled={isSubmitted}>
		Transfer 0.005 ETH to self</button
	>
	<button on:click={() => execute('1B1AE4D6E2EF500000', true)} disabled={isSubmitted}>
		Transfer 500 ETH to self</button
	>
	{#if txnHash}
		<p>Transaction hash: {txnHash}</p>
	{/if}
</div>
